yii/models/Customer.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "customer".
 *
 * @property integer $id_customer
 * @property integer $id_account
 * @property string $name
 * @property string $city
 * @property string $country
 * @property string $email
 * @property string $salary
 * @property string $transcript_attachment
 */
class Customer extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'customer';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_account', 'name', 'city', 'country', 'email', 'salary'], 'required'],
            [['id_customer', 'id_account'], 'integer'],
            [['salary'], 'number'],
            [['name', 'transcript_attachment'], 'string', 'max' => 255],
            [['city', 'country', 'email'], 'string', 'max' => 100],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_customer' => 'Id Customer',
            'id_account' => 'Id Account',
            'name' => 'Name',
            'city' => 'City',
            'country' => 'Country',
            'email' => 'Email',
            'salary' => 'Salary',
            'transcript_attachment' => 'Transcript Attachment',
        ];
    }
}

yii/controllers/CustomerController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Customer;
use app\models\CustomerSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * CustomerController implements the CRUD actions for Customer model.
 */
class CustomerController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'view', 'create', 'update','delete', 'loaddata', 'savedata'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Customer models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CustomerSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Customer model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Customer model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Customer();

        if ($model->load(Yii::$app->request->post())) {

            $randomString = Yii::$app->getSecurity()->generateRandomString(5);
            $token = Yii::$app->getSecurity()->generateRandomString(10);
            $nama_array = explode(" ",$model->name);
            $unique = date("s");

            $account = new \app\models\Account();            
            $account->username = strtolower($nama_array[0]).$unique;
            $account->password = md5($randomString);
            $account->role = "Customer";
            $account->token = $token;
            $account->save();

            $model->id_account = $account->id_account;
            $model->transcript_attachment = "-";
            if($model->save()){
                return $this->redirect(['view', 'id' => $model->id_customer]);
            }
            else{
                return var_dump($model->errors);
            }
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    public function actionLoaddata(){
        if(isset($_POST['url'])){
            $url = $_POST['url'];
            $load = file_get_contents($url);
            $data = json_decode($load);
            die(json_encode(array('note' => 'loaded', 'object' => $data->records)));
        }
    }

    public function actionSavedata(){
        $name = explode(",", $_POST['name']);
        $city = explode(",", $_POST['city']);
        $country = explode(",", $_POST['country']);
        $email = explode(",", $_POST['email']);
        $salary = explode(",", $_POST['salary']);
        $saved = FALSE;

        for($i = 0; $i < count($name); $i++){
            $model = new Customer();

            $randomString = Yii::$app->getSecurity()->generateRandomString(5);
            $token = Yii::$app->getSecurity()->generateRandomString(10);
            $nama_array = explode(" ",$model->name);
            $unique = date("s");

            $account = new \app\models\Account();            
            $account->username = strtolower($nama_array[0] != '' ? $nama_array[0]:$model->name).$unique;
            $account->password = md5($randomString);
            $account->role = "Customer";
            $account->token = $token;
            $account->save();

            $model->id_account = $account->id_account;
            $model->transcript_attachment = "-";
            $model->name = $name[$i];
            $model->city = $city[$i];
            $model->country = $country[$i];
            $model->email = $email[$i];
            $model->salary = $salary[$i];

            if($model->save()){
                $this->sendaccount($model->id_customer);
                $saved = TRUE;
            }
            else{
                $saved = FALSE;
            }
        }

        if($saved){
            die(json_encode(array('x' => 1, 'note' => 'success')));
        }
        else{
            die(json_encode(array('x' => 0, 'note' => 'failed')));
        }
    }

    public function Sendaccount($id){
        $customer = \app\models\Customer::find()->where(['id_customer' => $id])->one();
        $account = \app\models\Account::find()->where(['id_account' => $customer->id_account])->one();

        $link = \yii\helpers\Url::to('@web/account/confirmation/' . $account->id_account.'?token='.$account->token, true);

        try {
            $body = '<!DOCTYPE html>
                    <html>
                    <head>
                    </head>
                    <body>
                        Dear '.$customer->name.',<br><br>
                        <p> Akun Anda telah dibuat. Silahkan konfimasi akun dengan klik link berikut:</p>
                        <p>'.$link.'</p>
                        <p>Terima Kasih</p>
                    </body>
                </html>';
            $mail = new \PHPMailer(true);
            $mail->IsSMTP();
            $mail->SMTPDebug = 0;                     // enables SMTP debug information (for testing)
            $mail->SMTPAuth = true;                  // enable SMTP authentication
            $mail->SMTPSecure = "tls";                 // sets the prefix to the servier
            $mail->Host = "smtp.gmail.com";      // sets GMAIL as the SMTP server
            $mail->Port = 587;                   // set the SMTP port for the GMAIL server
            $mail->Username = "dummydidik@gmail.com";  // GMAIL username
            $mail->Password = "exyfhlpkhjewyktm";            // GMAIL password
            $mail->AddAddress($customer->email, $customer->email);
            $mail->SetFrom('no-reply@didik.net', 'no-reply@didik.net');
            $mail->Subject = "Account Confirmation";
            $mail->MsgHTML($body);
            $mail->Send();
        } catch (phpmailerException $e) {
            
        } catch (Exception $e) {
            
        }
    }

    /**
     * Updates an existing Customer model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_customer]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Customer model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Customer model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Customer the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Customer::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

yii/views/customer/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\Customer */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="customer-form">
    <div class="row">
        <div class="col-xs-4">
            <div  class="x_panel">
                <div class="x_title">
                    <h2><?= Html::encode($this->title) ?></h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">

                    <?php $form = ActiveForm::begin(); ?>

                    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

                    <?= $form->field($model, 'city')->textInput(['maxlength' => true]) ?>

                    <?= $form->field($model, 'country')->textInput(['maxlength' => true]) ?>

                    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

                    <?= $form->field($model, 'salary')->textInput(['maxlength' => true]) ?>

                    <div class="form-group">
                        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
                    </div>

                    <?php ActiveForm::end(); ?>
                </div>
            </div>
        </div>
        <div class="col-xs-8">
            <div class="row">
                <div class="col-xs-12">
                    <div  class="x_panel">
                        <div class="x_title">
                            <h2>Load Data Customer</h2>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">
                            <div class="form-group field-customer-name required">
                                <label class="control-label" for="customer-name">URL</label>
                                <input type="text" id="urldata" class="form-control" name="urldata">
                            </div>
                            <div class="form-group">
                                <a id="load" class="btn btn-success">Load</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>Data Loaded</h2>
                            <ul class="nav navbar-right panel_toolbox">
                                <li>
                                    <button class="btn btn-primary" id="clear"><i class="fa fa-refresh"></i></button>
                                </li>
                                <li>
                                    <button class="btn btn-success" id="save"><i class="fa fa-save"></i></button>
                                </li>
                            </ul>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">
                            <table class="table table-bordered" id="tabledata">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Name</th>
                                        <th>City</th>
                                        <th>Country</th>
                                        <th>Email</th>
                                        <th>Salary</th>                            
                                    </tr>
                                </thead>
                                <tbody>
                                    
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    window.name = [];
    window.city = [];
    window.country = [];
    window.email = [];
    window.salary = [];
    window.addEventListener('load', function(){
        window.loadcustomer = function(){
            $url = $('#urldata').val();
            $.post('<?= Url::to(["customer/loaddata"]) ?>',{
                _csrf: '<?= Yii::$app->request->getCsrfToken() ?>',
                url : $url,
            },function(data){
                var parsed = JSON.parse(data);
                var data = parsed.object;

                for(i=0; i< data.length; i++){
                    var html = $('#html_row').html();
                    html = html.substring(4, html.length - 3);
                    html = html.replace(new RegExp("_ID_", "g"), i);
                    $('#tabledata tbody').append(html);
                    if('Name' in data[i]){$('#name'+i+'').val(data[i]['Name']);}
                    if('City' in data[i]){$('#city'+i+'').val(data[i]['City']);}
                    if('Country' in data[i]){$('#contry'+i+'').val(data[i]['Country']);}
                    if('Email' in data[i]){$('#email'+i+'').val(data[i]['Email']);}
                    if('Salary' in data[i]){$('#salari'+i+'').val(data[i]['Salary']);}
                }
            });
        }

        $('#load').click(function(){
            loadcustomer();
        });

        window.savecustomer = function(){
            console.log('save data dipanggil');
            var name_ = [];
            var city_ = [];
            var country_ = [];
            var email_ = [];
            var salary_ = [];

            $('input[name="name"]').each(function () {
                name_.push($(this).val());
            });
            $('input[name="city"]').each(function () {
                city_.push($(this).val());
            });
            $('input[name="country"]').each(function () {
                country_.push($(this).val());
            });
            $('input[name="email"]').each(function () {
                email_.push($(this).val());
            });
            $('input[name="salary"]').each(function () {
                salary_.push($(this).val());
            });

            if(name_.length > 0 && city_.length > 0 && country_.length > 0 && email_.length > 0 && salary_.length > 0){
                console.log('proses ajax dimulai');
                $.post('<?= Url::to(["customer/savedata"]) ?>', {
                    _csrf: '<?= Yii::$app->request->getCsrfToken() ?>',
                    name : name_.join(","),
                    city : city_.join(","),
                    country : country_.join(","),
                    email : email_.join(","),
                    salary : salary_.join(","),
                }, function (data) {
                    console.log('feedback');
                    var parsed = JSON.parse(data);
                    if(parsed.x == 1){
                        $(function(){
                            new PNotify({
                                title: 'Data Customer',
                                text: 'Save data successfully',
                                type: 'info',
                                styling: 'bootstrap3',
                            });
                        });
                    }
                    else{
                        $(function(){
                            new PNotify({
                                title: 'Data Customer',
                                text: 'Save data failed',
                                type: 'danger',
                                styling: 'bootstrap3',
                            });
                        });
                    }
                });
            }
            else{
                $(function(){
                    new PNotify({
                        title: 'Data Customer',
                        text: 'Data Null',
                        type: 'info',
                        styling: 'bootstrap3',
                    });
                });
            }
        }

        $('#save').click(function(){
            savecustomer();
        });

        $('#clear').click(function(){
            $('#tabledata tbody').empty();
        });

        $('#tabledata').on('click', '.hapus', function () {
            if (confirm('Are you sure?')) {
                $(this).closest('tr').remove();
            }
        });
    });
</script>
<div id="html_row"><!--
    <tr id="_IT_">
        <td>
            <button class="btn btn-danger hapus"><i class="fa fa-times"></i></button>
        </td>
        <td><input type="text" class="form-control" name="name" id="name_ID_"></td>
        <td><input type="text" class="form-control" name="city" id="city_ID_"></td>
        <td><input type="text" class="form-control" name="country" id="contry_ID_"></td>
        <td><input type="text" class="form-control" name="email" id="email_ID_"></td>
        <td><input type="text" class="form-control" name="salary" id="salari_ID_"></td>        
</tr> -->
</div>

yii/views/customer/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\CustomerSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="customer-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id_customer') ?>

    <?= $form->field($model, 'id_account') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'city') ?>

    <?= $form->field($model, 'country') ?>

    <?php // echo $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'salary') ?>

    <?php // echo $form->field($model, 'transcript_attachment') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

yii/views/customer/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Customer */

$this->title = 'Create Customer';
$this->params['breadcrumbs'][] = ['label' => 'Customers', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="customer-create">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

yii/views/customer/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\CustomerSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Customers';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="customer-index">

    <div  class="x_panel">
        <div class="x_title">
            <h2><?= Html::encode($this->title) ?></h2>
            <ul class="nav navbar-right panel_toolbox">
                <li><p><?= Html::a('Add Customer', ['create'], ['class' => 'btn btn-success']) ?></p>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'columns' => [
                    ['class' => 'yii\grid\SerialColumn'],

                    // 'id_customer',
                    // 'id_account',
                    'name',
                    'city',
                    'country',
                    'email:email',
                    // 'salary',
                    // 'transcript_attachment',

                    ['class' => 'yii\grid\ActionColumn'],
                ],
            ]); ?>
        </div>
    </div>
</div>

yii/views/customer/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Customer */

$this->title = 'Update Customer: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Customers', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id_customer]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="customer-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

yii/views/customer/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Customer */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Customers', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="customer-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id_customer], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id_customer], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id_customer',
            'id_account',
            'name',
            'city',
            'country',
            'email:email',
            'salary',
            'transcript_attachment',
        ],
    ]) ?>

</div>