yii/models/CreditPropose.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "credit_propose".
 *
 * @property integer $id_credit_propose
 * @property integer $id_customer
 * @property string $propose_date
 * @property string $propose_status
 * @property string $approval_date
 */
class CreditPropose extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'credit_propose';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_customer', 'propose_date', 'propose_status', 'approval_date'], 'required'],
            [['id_credit_propose', 'id_customer'], 'integer'],
            [['propose_date', 'approval_date'], 'safe'],
            [['propose_status'], 'string', 'max' => 100],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_credit_propose' => 'Id Credit Propose',
            'id_customer' => 'Id Customer',
            'propose_date' => 'Propose Date',
            'propose_status' => 'Propose Status',
            'approval_date' => 'Approval Date',
        ];
    }
}

yii/controllers/CreditproposeController.php
<?php

namespace app\controllers;

use Yii;
use app\models\CreditPropose;
use app\models\CreditProposeSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CreditproposeController implements the CRUD actions for CreditPropose model.
 */
class CreditproposeController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    //'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all CreditPropose models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CreditProposeSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionPropose(){
        $model = new CreditPropose();
        $id_account = \Yii::$app->user->identity->id_account;
        $customer = \app\models\Customer::find()->where(['id_account' => $id_account])->one();

        $model->id_customer = $customer->id_customer;
        $model->propose_date = date("Y-m-d");
        $model->propose_status = 'Request';
        $model->approval_date = '0000-00-00';
        if($model->save()){
            return $this->redirect(['index']);
        }
        return $this->redirect(['index']);
    }

    public function actionApproval($id){
        $model = $this->findModel($id);
        $role = \Yii::$app->user->identity->role;
        if($model->propose_status == 'Request' && $role == 'Pemeriksa1'){
            $model->propose_status = 'Approved - Step 1';
            $model->approval_date = date("Y-m-d");
        }
        elseif($model->propose_status == 'Approved - Step 1' && $role == 'Pemeriksa2'){
            $model->propose_status = 'Approved - Step 2';
            $model->approval_date = date("Y-m-d");
        }
        elseif($model->propose_status == 'Approved - Step 2' && $role == 'Manager'){
            $model->propose_status = 'Approved - Step 3';
            $model->approval_date = date("Y-m-d");
            $this->notification($model->id_credit_propose);
        }
        
        if($model->save()){
            return $this->redirect(['index']);
        }
        return $this->redirect(['index']);
    }

    public function actionReject($id){
        $model = $this->findModel($id);
        $role = \Yii::$app->user->identity->role;
        if($model->propose_status == 'Request' && $role == 'Pemeriksa1'){
            $model->propose_status = 'Rejected - Step 1';
            $model->approval_date = date("Y-m-d");
        }
        elseif($model->propose_status == 'Approved - Step 1' && $role == 'Pemeriksa2'){
            $model->propose_status = 'Rejected - Step 2';
            $model->approval_date = date("Y-m-d");
        }
        elseif($model->propose_status == 'Approved - Step 2' && $role == 'Manager'){
            $model->propose_status = 'Rejected - Step 3';
            $model->approval_date = date("Y-m-d");
        }
        
        if($model->save()){
            return $this->redirect(['index']);
        }
        return $this->redirect(['index']);
    }

    public function Notification($id){
        $propose = $this->findModel($id);
        $customer = \app\models\Customer::find()->where(['id_customer' => $propose->id_customer])->one();
        try {
            $body = '<!DOCTYPE html>
                    <html>
                    <head>
                    </head>
                    <body>
                        Dear '.$customer->name.',<br><br>
                        <p>Pengajuan kredit kendaraan Anda telah di terima.</p>
                        <p>Terima Kasih</p>
                    </body>
                </html>';
            $mail = new \PHPMailer(true);
            $mail->IsSMTP();
            $mail->SMTPDebug = 0;                     // enables SMTP debug information (for testing)
            $mail->SMTPAuth = true;                  // enable SMTP authentication
            $mail->SMTPSecure = "tls";                 // sets the prefix to the servier
            $mail->Host = "smtp.gmail.com";      // sets GMAIL as the SMTP server
            $mail->Port = 587;                   // set the SMTP port for the GMAIL server
            $mail->Username = "dummydidik@gmail.com";  // GMAIL username
            $mail->Password = "exyfhlpkhjewyktm";            // GMAIL password
            $mail->AddAddress($customer->email, $customer->email);
            $mail->SetFrom('no-reply@didik.net', 'no-reply@didik.net');
            $mail->Subject = "Account Confirmation";
            $mail->MsgHTML($body);
            $mail->Send();
        } catch (phpmailerException $e) {
            
        } catch (Exception $e) {
            
        }
    }

    /**
     * Displays a single CreditPropose model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new CreditPropose model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new CreditPropose();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_credit_propose]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing CreditPropose model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_credit_propose]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing CreditPropose model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the CreditPropose model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return CreditPropose the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = CreditPropose::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

yii/views/creditpropose/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\CreditPropose */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="credit-propose-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'id_credit_propose')->textInput() ?>

    <?= $form->field($model, 'id_customer')->textInput() ?>

    <?= $form->field($model, 'propose_date')->textInput() ?>

    <?= $form->field($model, 'propose_status')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'approval_date')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

yii/views/creditpropose/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\CreditProposeSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="credit-propose-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id_credit_propose') ?>

    <?= $form->field($model, 'id_customer') ?>

    <?= $form->field($model, 'propose_date') ?>

    <?= $form->field($model, 'propose_status') ?>

    <?= $form->field($model, 'approval_date') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

yii/views/creditpropose/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\CreditPropose */

$this->title = 'Create Credit Propose';
$this->params['breadcrumbs'][] = ['label' => 'Credit Proposes', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="credit-propose-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

yii/views/creditpropose/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel app\models\CreditProposeSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Credit Proposes';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="credit-propose-index">
    <div  class="x_panel">
        <div class="x_title">
            <h2><?= Html::encode($this->title) ?></h2>
            <ul class="nav navbar-right panel_toolbox">
                <li>
                    <?php if(\Yii::$app->user->identity->role == 'Customer'): ?>
                    <p>
                        <?= Html::a('Propose Credit', ['propose'], ['class' => 'btn btn-success']) ?>
                    </p>
                    <?php endif; ?>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'columns' => [
                    ['class' => 'yii\grid\SerialColumn'],
                    [
                        'attribute' => 'group',
                        'header' => '&nbsp',
                        'format' => 'raw',
                        'value' => function($model) {
                            $view_url = Url::to(['creditpropose/view', 'id' => $model->id_credit_propose]);
                            $delete_url = Url::to(['creditpropose/delete', 'id' => $model->id_credit_propose]);
                            $approval_url = Url::to(['creditpropose/approval', 'id' => $model->id_credit_propose]);
                            $reject_url = Url::to(['creditpropose/reject', 'id' => $model->id_credit_propose]);
                            return '<div class="btn-group dropup">
                                      <button class="btn blue dropdown-toggle" type="button" data-toggle="dropdown">
                                        Action <i class="fa fa-angle-up"></i>
                                      </button>
                                      <ul class="dropdown-menu" role="menu">
                                        '.((\Yii::$app->user->identity->role != 'Customer')? ''.((substr($model->propose_status, 0, 8) != 'Rejected' && $model->propose_status != 'Approved - Step 3')? '<li><a href="#" onclick="top.location.href=\'' . $approval_url . '\';return false"><i class="fa fa-check-square"></i> Appove</a></li>':'').'
                                        '.(($model->propose_status != 'Approved - Step 3' && substr($model->propose_status, 0, 8) != 'Rejected')? '<li><a href="#" onclick="top.location.href=\'' . $reject_url . '\';return false"><i class="fa fa-close"></i> Reject</a></li>':'').'
                                        ':'').'
                                        <li><a href="#" onclick="top.location.href=\'' . $view_url . '\';return false"><i class="fa fa-eye"></i> View</a></li>
                                        '.((\Yii::$app->user->identity->role != 'Customer')? '<li><a href="#" onclick="top.location.href=\'' . $delete_url . '\';return false"><i class="fa fa-trash"></i> Delete</a></li>':'').'
                                      </ul>
                                    </div>';
                        }
                    ],
                    'propose_date',
                    'propose_status',
                    'approval_date',
                ],
            ]); ?>
        </div>
    </div>
</div>

yii/views/creditpropose/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\CreditPropose */

$this->title = 'Update Credit Propose: ' . $model->id_credit_propose;
$this->params['breadcrumbs'][] = ['label' => 'Credit Proposes', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id_credit_propose, 'url' => ['view', 'id' => $model->id_credit_propose]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="credit-propose-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

yii/views/creditpropose/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\CreditPropose */

$this->title = $model->id_credit_propose;
$this->params['breadcrumbs'][] = ['label' => 'Credit Proposes', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="credit-propose-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id_credit_propose], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id_credit_propose], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id_credit_propose',
            'id_customer',
            'propose_date',
            'propose_status',
            'approval_date',
        ],
    ]) ?>

</div>