yii/controllers/AccountController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Account;
use app\models\AccountSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * AccountController implements the CRUD actions for Account model.
 */
class AccountController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Account models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new AccountSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Account model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Account model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Account();

        if ($model->load(Yii::$app->request->post())) {
            $model->password = md5($model->password);
            if($model->save()){
                return $this->redirect(['view', 'id' => $model->id_account]);
            }            
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Account model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_account]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Account model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Account model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Account the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Account::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

yii/controllers/CustomerController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Customer;
use app\models\CustomerSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * CustomerController implements the CRUD actions for Customer model.
 */
class CustomerController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'view', 'create', 'update','delete', 'loaddata', 'savedata'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Customer models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CustomerSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Customer model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Customer model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Customer();

        if ($model->load(Yii::$app->request->post())) {

            $randomString = Yii::$app->getSecurity()->generateRandomString(5);
            $token = Yii::$app->getSecurity()->generateRandomString(10);
            $nama_array = explode(" ",$model->name);
            $unique = date("s");

            $account = new \app\models\Account();            
            $account->username = strtolower($nama_array[0]).$unique;
            $account->password = md5($randomString);
            $account->role = "Customer";
            $account->token = $token;
            $account->save();

            $model->id_account = $account->id_account;
            $model->transcript_attachment = "-";
            if($model->save()){
                return $this->redirect(['view', 'id' => $model->id_customer]);
            }
            else{
                return var_dump($model->errors);
            }
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    public function actionLoaddata(){
        if(isset($_POST['url'])){
            $url = $_POST['url'];
            $load = file_get_contents($url);
            $data = json_decode($load);
            die(json_encode(array('note' => 'loaded', 'object' => $data->records)));
        }
    }

    public function actionSavedata(){
        $name = explode(",", $_POST['name']);
        $city = explode(",", $_POST['city']);
        $country = explode(",", $_POST['country']);
        $email = explode(",", $_POST['email']);
        $salary = explode(",", $_POST['salary']);
        $saved = FALSE;

        for($i = 0; $i < count($name); $i++){
            $model = new Customer();

            $randomString = Yii::$app->getSecurity()->generateRandomString(5);
            $token = Yii::$app->getSecurity()->generateRandomString(10);
            $nama_array = explode(" ",$model->name);
            $unique = date("s");

            $account = new \app\models\Account();            
            $account->username = strtolower($nama_array[0] != '' ? $nama_array[0]:$model->name).$unique;
            $account->password = md5($randomString);
            $account->role = "Customer";
            $account->token = $token;
            $account->save();

            $model->id_account = $account->id_account;
            $model->transcript_attachment = "-";
            $model->name = $name[$i];
            $model->city = $city[$i];
            $model->country = $country[$i];
            $model->email = $email[$i];
            $model->salary = $salary[$i];

            if($model->save()){
                $this->sendaccount($model->id_customer);
                $saved = TRUE;
            }
            else{
                $saved = FALSE;
            }
        }

        if($saved){
            die(json_encode(array('x' => 1, 'note' => 'success')));
        }
        else{
            die(json_encode(array('x' => 0, 'note' => 'failed')));
        }
    }

    public function Sendaccount($id){
        $customer = \app\models\Customer::find()->where(['id_customer' => $id])->one();
        $account = \app\models\Account::find()->where(['id_account' => $customer->id_account])->one();

        $link = \yii\helpers\Url::to('@web/account/confirmation/' . $account->id_account.'?token='.$account->token, true);

        try {
            $body = '<!DOCTYPE html>
                    <html>
                    <head>
                    </head>
                    <body>
                        Dear '.$customer->name.',<br><br>
                        <p> Akun Anda telah dibuat. Silahkan konfimasi akun dengan klik link berikut:</p>
                        <p>'.$link.'</p>
                        <p>Terima Kasih</p>
                    </body>
                </html>';
            $mail = new \PHPMailer(true);
            $mail->IsSMTP();
            $mail->SMTPDebug = 0;                     // enables SMTP debug information (for testing)
            $mail->SMTPAuth = true;                  // enable SMTP authentication
            $mail->SMTPSecure = "tls";                 // sets the prefix to the servier
            $mail->Host = "smtp.gmail.com";      // sets GMAIL as the SMTP server
            $mail->Port = 587;                   // set the SMTP port for the GMAIL server
            $mail->Username = "dummydidik@gmail.com";  // GMAIL username
            $mail->Password = "exyfhlpkhjewyktm";            // GMAIL password
            $mail->AddAddress($customer->email, $customer->email);
            $mail->SetFrom('no-reply@didik.net', 'no-reply@didik.net');
            $mail->Subject = "Account Confirmation";
            $mail->MsgHTML($body);
            $mail->Send();
        } catch (phpmailerException $e) {
            
        } catch (Exception $e) {
            
        }
    }

    /**
     * Updates an existing Customer model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_customer]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Customer model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Customer model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Customer the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Customer::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

yii/controllers/EmployeeController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Employee;
use app\models\EmployeeSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * EmployeeController implements the CRUD actions for Employee model.
 */
class EmployeeController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Employee models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new EmployeeSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Employee model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Employee model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Employee();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_employee]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Employee model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_employee]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Employee model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Employee model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Employee the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Employee::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

yii/views/layouts/main.php
<?php 
use yii\helpers\Url;
use yii\widgets\Breadcrumbs;
use yii\helpers\Html;
use yii\web\View;

$c = $this->context->id;

 ?>
 <!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title><?php $this->title ?>Vehicle Loans</title>

    <!-- Bootstrap -->
    <link href="<?php echo \yii::$app->view->theme->baseUrl; ?>/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="<?php echo \yii::$app->view->theme->baseUrl; ?>/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="<?php echo \yii::$app->view->theme->baseUrl; ?>/vendors/nprogress/nprogress.css" rel="stylesheet">

    <!-- PNotify -->
    <link href="<?php echo \yii::$app->view->theme->baseUrl; ?>/vendors/pnotify/dist/pnotify.css" rel="stylesheet">
    <link href="<?php echo \yii::$app->view->theme->baseUrl; ?>/vendors/pnotify/dist/pnotify.buttons.css" rel="stylesheet">
    <link href="<?php echo \yii::$app->view->theme->baseUrl; ?>/vendors/pnotify/dist/pnotify.nonblock.css" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="<?php echo \yii::$app->view->theme->baseUrl; ?>/build/css/custom.min.css" rel="stylesheet">
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="" class="site_title"><i class="fa fa-car"></i> <span>Vehicle Loans</span></a>
            </div>

            <div class="clearfix"></div>

            <!-- menu profile quick info -->
            <div class="profile">
              <div class="profile_pic">
                <img src="<?php echo \yii::$app->view->theme->baseUrl; ?>/production/images/img.jpg" alt="..." class="img-circle profile_img">
              </div>
              <div class="profile_info">
                <span>Welcome,</span>
                <h2><?=\Yii::$app->user->identity->username?></h2>
              </div>
            </div>
            <!-- /menu profile quick info -->

            <br />

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <h3>&nbsp;</h3>
              </div>
              <div class="menu_section">
                <ul class="nav side-menu">
                  <li class="<?= ($c == 'site') ? 'current-page' : '' ?>">
                    <a href="<?= Url::to(['site/index']) ?>">
                      <i class="fa fa-home"></i> Home</span>
                    </a>
                  </li>
                  <?php if(Yii::$app->user->identity->role == 'Manager'): ?>
                  <li class="<?= ($c == 'account') ? 'current-page' : '' ?>">
                    <a href="<?= Url::to(['account/index']) ?>">
                      <i class="fa fa-user"></i> Account</span>
                    </a>
                  </li>
                  <?php endif; ?>
                  <li class="<?= ($c == 'creditpropose') ? 'current-page' : '' ?>">
                    <a href="<?= Url::to(['creditpropose/index']) ?>">
                      <i class="fa fa-file"></i> Credit Propose</span>
                    </a>
                  </li>
                  <?php if(Yii::$app->user->identity->role != 'Customer'): ?>
                  <li class="<?= ($c == 'account') ? 'current-page' : '' ?>">
                    <a href="<?= Url::to(['customer/index']) ?>">
                      <i class="fa fa-user"></i> Customer</span>
                    </a>
                  </li>
                  <?php endif; ?>
                  <?php if(Yii::$app->user->identity->role != 'Customer'): ?>
                  <li class="<?= ($c == 'employee') ? 'current-page' : '' ?>">
                    <a href="<?= Url::to(['employee/index']) ?>">
                      <i class="fa fa-user"></i> Employee</span>
                    </a>
                  </li>
                  <?php endif; ?>
                </ul>
              </div>

            </div>
            <!-- /sidebar menu -->

            <!-- /menu footer buttons -->
            <div class="sidebar-footer hidden-small">
              <a data-toggle="tooltip" data-placement="top" title="Settings">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="Lock">
                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="Logout">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
              </a>
            </div>
            <!-- /menu footer buttons -->
          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>

              <ul class="nav navbar-nav navbar-right">
                <li class="">
                  <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <img src="<?php echo \yii::$app->view->theme->baseUrl; ?>/production/images/img.jpg" alt=""><?=\Yii::$app->user->identity->username?>
                    <span class=" fa fa-angle-down"></span>
                  </a>
                  <ul class="dropdown-menu dropdown-usermenu pull-right">
                    <li><a href="#" onclick="$('#form-logout').submit();return false"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                  </ul>
                </li>
              </ul>
              <form method="post" action="<?= Url::to(['site/logout']) ?>" id="form-logout">
                  <input type="hidden"name="_csrf" value="<?= Yii::$app->request->getCsrfToken() ?>">
              </form>
            </nav>
          </div>
        </div>
        <!-- /top navigation -->

        <!-- page content -->
        <div class="right_col" role="main">
          <div>
            <div class="row top_tiles">
              <?=
                Breadcrumbs::widget([
                    'options' => [
                        'class' => 'breadcrumb',
                    ],
                    'itemTemplate' => "<li> {link} </li>\n",
                    'homeLink' => [
                        'label' => Yii::t('yii', 'Home'),
                        'url' => Yii::$app->homeUrl,
                    ],
                    'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                ])
              ?>
              <?= $content ?>
            </div>
          </div>
        </div>
        <!-- /page content -->

        <!-- footer content -->
        <footer>
          <div class="pull-right">
            Didik Wibowo - Vehicle Loans &copy; 2016
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
      </div>
    </div>

    <!-- jQuery -->
    <script src="<?php echo \yii::$app->view->theme->baseUrl; ?>/vendors/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="<?php echo \yii::$app->view->theme->baseUrl; ?>/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- FastClick -->
    <!-- <script src="<?php echo \yii::$app->view->theme->baseUrl; ?>/vendors/fastclick/lib/fastclick.js"></script> -->
    <!-- NProgress -->
    <!-- <script src="<?php echo \yii::$app->view->theme->baseUrl; ?>/vendors/nprogress/nprogress.js"></script> -->
    <!-- Chart.js -->
    <!-- <script src="<?php echo \yii::$app->view->theme->baseUrl; ?>/vendors/Chart.js/dist/Chart.min.js"></script> -->
    <!-- jQuery Sparklines -->
    <!-- <script src="<?php echo \yii::$app->view->theme->baseUrl; ?>/vendors/jquery-sparkline/dist/jquery.sparkline.min.js"></script> -->
    <!-- Flot -->
    <!-- <script src="<?php echo \yii::$app->view->theme->baseUrl; ?>/vendors/Flot/jquery.flot.js"></script>
    <script src="<?php echo \yii::$app->view->theme->baseUrl; ?>/vendors/Flot/jquery.flot.pie.js"></script>
    <script src="<?php echo \yii::$app->view->theme->baseUrl; ?>/vendors/Flot/jquery.flot.time.js"></script>
    <script src="<?php echo \yii::$app->view->theme->baseUrl; ?>/vendors/Flot/jquery.flot.stack.js"></script>
    <script src="<?php echo \yii::$app->view->theme->baseUrl; ?>/vendors/Flot/jquery.flot.resize.js"></script> -->
    <!-- Flot plugins -->
    <!-- <script src="<?php echo \yii::$app->view->theme->baseUrl; ?>/vendors/flot.orderbars/js/jquery.flot.orderBars.js"></script>
    <script src="<?php echo \yii::$app->view->theme->baseUrl; ?>/vendors/flot-spline/js/jquery.flot.spline.min.js"></script>
    <script src="<?php echo \yii::$app->view->theme->baseUrl; ?>/vendors/flot.curvedlines/curvedLines.js"></script> -->
    <!-- DateJS -->
    <!-- <script src="<?php echo \yii::$app->view->theme->baseUrl; ?>/vendors/DateJS/build/date.js"></script> -->
    <!-- bootstrap-daterangepicker -->
    <!-- <script src="<?php echo \yii::$app->view->theme->baseUrl; ?>/production/js/moment/moment.min.js"></script>
    <script src="<?php echo \yii::$app->view->theme->baseUrl; ?>/production/js/datepicker/daterangepicker.js"></script> -->
    <script src="<?php echo \yii::$app->view->theme->baseUrl; ?>/vendors/pnotify/dist/pnotify.js"></script>
    <script src="<?php echo \yii::$app->view->theme->baseUrl; ?>/vendors/pnotify/dist/pnotify.buttons.js"></script>
    <script src="<?php echo \yii::$app->view->theme->baseUrl; ?>/vendors/pnotify/dist/pnotify.nonblock.js"></script>
    <!-- Custom Theme Scripts -->
    <script src="<?php echo \yii::$app->view->theme->baseUrl; ?>/build/js/custom.min.js"></script>

    <script>
      
    </script>
  </body>
</html>